x-minio-common: &minio-common
  image: minio/minio:RELEASE.2025-06-13T11-33-47Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}

  expose:
    - "9000"
    - "9001"

  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5


services:

  # ==============================
  # MongoDB
  # ==============================
  mongodb:
    image: mongo:7
    container_name: async-image-mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongodb_data:/data/db


  # ==============================
  # RabbitMQ
  # ==============================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: async-image-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  # ==============================
  # Distributed MinIO Cluster
  # ==============================
  minio1:
    <<: *minio-common
    container_name: async-image-minio1
    hostname: minio1

    volumes:
      - minio1_data1:/data1
      - minio1_data2:/data2


  minio2:
    <<: *minio-common
    container_name: async-image-minio2
    hostname: minio2

    volumes:
      - minio2_data1:/data1
      - minio2_data2:/data2


  minio3:
    <<: *minio-common
    container_name: async-image-minio3
    hostname: minio3

    volumes:
      - minio3_data1:/data1
      - minio3_data2:/data2


  minio4:
    <<: *minio-common
    container_name: async-image-minio4
    hostname: minio4

    volumes:
      - minio4_data1:/data1
      - minio4_data2:/data2

  minio-nginx:
    image: nginx:alpine
    container_name: async-image-minio-nginx

    volumes:
      - ./nginx/minio.conf:/etc/nginx/nginx.conf:ro

    expose:
      - "9000"
      - "9001"

    depends_on:
      minio1:
        condition: service_healthy
      minio2:
        condition: service_healthy
      minio3:
        condition: service_healthy
      minio4:
        condition: service_healthy

  minio-init: #minio cluster başlatıldıktan sonra bucket oluşturmak için kullanılan servis
    image: minio/mc:RELEASE.2025-05-21T01-59-54Z
    container_name: async-image-minio-init

    depends_on:
      minio1:
        condition: service_healthy
      minio2:
        condition: service_healthy
      minio3:
        condition: service_healthy
      minio4:
        condition: service_healthy
      minio-nginx:
        condition: service_started

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio-nginx:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      mc mb --ignore-existing minio/images; 
      exit 0;
      "

  backend:
    build:
      context: ./backend
    container_name: async-image-backend

    environment:
      PORT: 4000
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/metadata?authSource=admin
      RABBITMQ_URI: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      ENDPOINT: http://minio-nginx:9000
      BUCKET: images
      ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}

    expose:
      - "4000"

    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
      minio-nginx:
        condition: service_started


  worker:
    build:
      context: ./worker
    container_name: async-image-worker

    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/metadata?authSource=admin
      RABBITMQ_URI: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      ENDPOINT: http://minio-nginx:9000
      BUCKET: images
      ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}

    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
      minio-nginx:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    container_name: async-image-frontend

    expose:
      - "80"


# ==============================
# Persistent Volumes
# ==============================
volumes:

  mongodb_data:
  rabbitmq_data:

  minio1_data1:
  minio1_data2:

  minio2_data1:
  minio2_data2:

  minio3_data1:
  minio3_data2:

  minio4_data1:
  minio4_data2: